    <a href="index.html">
        <img id=book_smart_logo src="Images/BookSmart_Digital_logo_CAF0F8_background.png"
            alt="BookSmart Digital Company Logo" title="To home page">
    </a>
    <nav>
        <ul>
            <li><a href="pages/index.php" target="_self">Homepage</a></li>
            <li><a href="pages/apply.php" target="_self">Applications</a></li>
            <li><a href="pages/jobs.php" target="_self">Jobs</a></li>
            <li><a href="pages/about.php" target="_self">About</a></li>
            <li><a href="pages/login.php" target="_self">Login</a></li>

        </ul>
    </nav>

    <form>
        <label for="search">Search:</label>
        <input type="text" id="search" name = "search" placeholder="jobs, about, etc.">
        <button type="submit">Search</button>
    </form>

    <hr id = head_line>