    <a href="index.php">
        <img id=book_smart_logo src="../Images/booksmartdigital.png"
            alt="BookSmart Digital Company Logo" title="To home page">
    </a>
    <nav>
        <ul>
            <li><a href="index.php" target="_self">Homepage</a></li>
            <li><a href="apply.php" target="_self">Applications</a></li>
            <li><a href="jobs.php" target="_self">Jobs</a></li>
            <li><a href="about.php" target="_self">About</a></li>
            <li><a href="login.php" target="_self">Manager Login</a></li>

        </ul>
    </nav>

    <h1 style="text-align: center;">BookSmart Digital</h1>

    <hr style="height: 3px; border: none; background-color: black;">